name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Instalar html5validator
      run: sudo pip install html5validator
    
    - name: Validar HTML5
      run: html5validator --root _build/
    
    - name: Instalar Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - name: Instalar Surge
      run: npm install -g surge
    
    - name: Desplegar en Surge
      run: surge ./_build/ mi-prueba-jose123.surge.sh --token ${{ secrets.SURGE_TOKEN }}
